export const NotificationType = {
  SYSTEM_LOG: "SYSTEM_LOG",
  CHAT_MENTION: "CHAT_MENTION",
  CHAT_GROUP: "CHAT_GROUP",
  ARTICLE_CREATED: "ARTICLE_CREATED",
  ARTICLE_DELETED: "ARTICLE_DELETED",
  ARTICLE_UPDATED: "ARTICLE_UPDATED",
  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCT_DELETED: "PRODUCT_DELETED",
  PRODUCT_UPDATED: "PRODUCT_UPDATED",
  USER_CREATED: "USER_CREATED",
  USER_DISABLED: "USER_DISABLED",
  USER_UPDATED: "USER_UPDATED",
} as const;

export type NotificationType =
  (typeof NotificationType)[keyof typeof NotificationType];
